const DISABLE_TOKENIZE_WIDGET_EVENT_NAME = 'disableGeFormWidgetTokenizeCard';
const LABEL_NEW_LINE = '/0x0A/';
const WIDGET_TYPE_DI_FIELD_VALUE = 'DI_FIELD_VALUE';

export {
    DISABLE_TOKENIZE_WIDGET_EVENT_NAME,
    LABEL_NEW_LINE,
    WIDGET_TYPE_DI_FIELD_VALUE,
};