<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.BatchJobId__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.ChildBatchCount__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.DMLOperationCount__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.DMLRows__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.Duration__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.EndDate__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.RecordsModifiedCount__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.RecordsProcessedCount__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>BatchResultLog__c.StartDate__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <objectPermissions>
        <object>BatchResultLog__c</object>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
    </objectPermissions>
    <tabVisibilities>
        <tab>BatchResultLog__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>
