/*
    Copyright (c) 2015, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2015
* @group Opportunity
* @group-content ../../ApexDocContent/Opportunity.htm
* @description Controller for button that calculates Opportunity name for a single Opportunity.
*/
public with sharing class OPP_OpportunityNamingBTN_CTRL {
    
    private ApexPages.StandardController ctrl;
    public Boolean redirect {get; set;}

    /** @description Standard opportunity controller constructor.*/
    public OPP_OpportunityNamingBTN_CTRL(ApexPages.StandardController oppCtrl) {
        ctrl = oppCtrl;
    }

    /** @description Button click method runs opportunity naming for the current opportunity.*/
    public PageReference buttonClick() {
        if (ctrl.getId() == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Missing Id'));
            return null;
        }
        list<Opportunity> thisOpp = new list<Opportunity>{(Opportunity)ctrl.getRecord()};

        if (!thisOpp.isEmpty()) {
            try {
                if (!UTIL_Permissions.canUpdate('Opportunity', 'Name', false)) {
                    throw new UTIL_Permissions.InsufficientPermissionException(System.Label.commonAccessErrorMessage);
                }
                OPP_OpportunityNaming.refreshOppNames(thisOpp);
                update thisOpp;
                redirect = true;
            } catch (Exception ex) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                redirect = false;
            }
        }
        return null;
    }
}